# Generated by Django 3.1.7 on 2021-04-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('f_name', models.CharField(default='First Name', max_length=999, primary_key=True, serialize=False)),
                ('l_name', models.CharField(default='Last Name', max_length=999)),
                ('phone_number', models.CharField(default='Phone Number', max_length=999)),
                ('email', models.CharField(default='Enter your email', max_length=999)),
                ('address', models.CharField(default='Enter Local Address', max_length=999)),
                ('password', models.CharField(default='YOUR PASSWORD', max_length=999)),
            ],
        ),
    ]
